// "use client";

// import { useState, useRef } from "react";
// import Image from "next/image";
// import { X, Maximize2 } from "lucide-react";

// interface GalleryGridProps {
//   filePaths: string[];
//   title: string;
// }

// const THUMBNAIL_BASE = "https://image.tmdb.org/t/p/w780";
// const ORIGINAL_BASE = "https://image.tmdb.org/t/p/original";

// export function GalleryGrid({ filePaths, title }: GalleryGridProps) {
//   const [activeImage, setActiveImage] = useState<string | null>(null);
//   const lastTap = useRef<number | null>(null);

//   // Pure Cross-device Double Tap handler using native event timestamps
//   const handleDoubleTap = (
//     e: React.MouseEvent | React.TouchEvent,
//     path: string,
//   ) => {
//     const now = e.timeStamp; // Pure browser property generated by user interaction
//     const DOUBLE_PRESS_DELAY = 300; // ms

//     if (lastTap.current && now - lastTap.current < DOUBLE_PRESS_DELAY) {
//       setActiveImage(path);
//       lastTap.current = null; // Clear to prevent sticky triple-taps
//     } else {
//       lastTap.current = now;
//     }
//   };

//   if (!filePaths.length) {
//     return (
//       <div className="rounded-2xl border border-dashed border-zinc-800 p-12 text-center">
//         <p className="text-sm text-zinc-500">
//           No media backdrops found for this title.
//         </p>
//       </div>
//     );
//   }

//   return (
//     <>
//       {/* Grid Display Layer */}
//       <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4 md:gap-6">
//         {filePaths.map((path, idx) => (
//           <div
//             key={path}
//             onClick={(e) => handleDoubleTap(e, path)}
//             onDoubleClick={() => setActiveImage(path)}
//             className="group relative aspect-video cursor-zoom-in overflow-hidden rounded-xl border border-white/5 bg-zinc-950 transition-all duration-300 hover:border-white/20 select-none touch-manipulation"
//           >
//             <Image
//               src={`${THUMBNAIL_BASE}${path}`}
//               alt={`${title} snapshot ${idx + 1}`}
//               fill
//               loading="lazy"
//               sizes="(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw"
//               className="object-cover transition-transform duration-500 group-hover:scale-102"
//             />
//             {/* Soft Hover Overlay Hint */}
//             <div className="absolute inset-0 bg-black/40 opacity-0 group-hover:opacity-100 transition-opacity flex items-center justify-center pointer-events-none">
//               <div className="flex items-center gap-2 rounded-full bg-black/70 border border-white/10 px-3 py-1.5 backdrop-blur-md">
//                 <Maximize2 className="h-3 w-3 text-white" />
//                 <span className="text-[10px] uppercase font-black tracking-wider text-white">
//                   Double Tap Preview
//                 </span>
//               </div>
//             </div>
//           </div>
//         ))}
//       </div>

//       {/* Screen-size Interactive Preview Lightbox Modal */}
//       {activeImage && (
//         <div
//           className="fixed inset-0 z-50 flex items-center justify-center bg-black/95 backdrop-blur-xl p-2 sm:p-4 select-none"
//           onClick={() => setActiveImage(null)}
//         >
//           {/* Top Control Header */}
//           <div className="absolute top-4 right-4 z-50 flex items-center gap-4">
//             <button
//               onClick={() => setActiveImage(null)}
//               className="flex h-10 w-10 items-center justify-center rounded-full bg-white/5 border border-white/10 text-white backdrop-blur-md transition-transform hover:scale-105 active:scale-95"
//             >
//               <X className="h-5 w-5" />
//             </button>
//           </div>

//           {/* Large Aspect Controlled Image Frame */}
//           <div
//             className="relative w-full max-w-6xl aspect-video overflow-hidden rounded-xl border border-white/10 shadow-2xl"
//             onClick={(e) => e.stopPropagation()}
//           >
//             <Image
//               src={`${ORIGINAL_BASE}${activeImage}`}
//               alt="Fullscreen Backdrop Preview"
//               fill
//               priority
//               className="object-contain"
//               sizes="100vw"
//             />
//           </div>
//         </div>
//       )}
//     </>
//   );
// }
